name: Deploy

on:
  push:
    branches:
      - master

jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Add Heroku remote
        run: heroku git:remote -a python-simple-server
      - name: Push to Heroku
        run: git push heroku master